version: '3.8'

services:
  db:
    image: postgres:15
    container_name: nest-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agente_corretor
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: nest-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pgdata:






